In [1]:
# import essential libraries

import numpy as np
import pandas as pd

In [2]:
# load addresses.csv file

addresses_df=pd.read_csv("C:/Users/Sistech Computer/OneDrive/Desktop/sandeep/enterprice-banking-analytics-system/data/raw/addresses.csv")
addresses_df.head()

   AddressID       Street            City        Country
0        706      Edgardo        Stafford  United States
1        969     Fernwood       Opelousas  United States
2        129  Double Rock       Claremore  United States
3        780         Avon  Universal City            NaN
4        652          Dow       Covington  United States

In [3]:
# check the size of addresses.csv file
addresses_df.shape

(1222, 4)

In [4]:
# check datatypes of addresses.csv
addresses_df.dtypes

AddressID    int64
Street         str
City           str
Country        str
dtype: object

In [5]:
# print last row
addresses_df.tail()

      AddressID           Street             City        Country
1217        936  Diamond Heights  West Des Moines  United States
1218        586           Prague        Milwaukie  United States
1219        559         Rousseau       Port Huron  United States
1220        207      Double Rock           Lenexa  United States
1221        646            Flood        Avon Lake  United States

In [6]:
# describe the dataset
addresses_df.describe()

         AddressID
count  1222.000000
mean    603.732406
std     349.526435
min       1.000000
25%     301.250000
50%     602.500000
75%     905.750000
max    1210.000000

In [7]:
# check the missing values
addresses_df.isnull().sum()

AddressID     0
Street       24
City         26
Country      24
dtype: int64

In [8]:
# fill the missing values
addresses_df['Street']=addresses_df['Street'].fillna('Unknown')
addresses_df['City']=addresses_df['City'].fillna(addresses_df['City'].mode()[0])
addresses_df['Country']=addresses_df['Country'].ffill()

In [9]:
# check duplicates values
addresses_df.duplicated().sum()

np.int64(12)

In [10]:
# delete duplicate values
addresses_df.drop_duplicates()

addresses_df.head()

   AddressID       Street            City        Country
0        706      Edgardo        Stafford  United States
1        969     Fernwood       Opelousas  United States
2        129  Double Rock       Claremore  United States
3        780         Avon  Universal City  United States
4        652          Dow       Covington  United States

In [11]:
# save this file 
addresses_df.to_csv('cleaned_addresses.csv', index=False)

print('Saved file successfully....')

Saved file successfully....

In [12]:
# load customer_types.csv file

customer_types_df=pd.read_csv("C:/Users/Sistech Computer/OneDrive/Desktop/sandeep/enterprice-banking-analytics-system/data/raw/customer_types.csv")
customer_types_df.head()

   CustomerTypeID          TypeName
0               1        Individual
1               2    Small Business
2               3  Large Enterprise

In [13]:
# check the size of customer_types.csv
customer_types_df.shape

(3, 2)

In [14]:
# check the datatypes
customer_types_df.dtypes

CustomerTypeID    int64
TypeName            str
dtype: object

In [15]:
# check missing values
customer_types_df.isnull().sum()

CustomerTypeID    0
TypeName          0
dtype: int64

In [16]:
# check duplicates values
customer_types_df.duplicated().sum()

np.int64(0)

In [17]:
# save this file 
customer_types_df.to_csv('cleaned_customers_types.csv', index=False)

print('Saved file successfully....')

Saved file successfully....

In [18]:
# load customer_types.csv file

account_types_df=pd.read_csv("C:/Users/Sistech Computer/OneDrive/Desktop/sandeep/enterprice-banking-analytics-system/data/raw/account_types.csv")
account_types_df.head()

   AccountTypeID  TypeName
0              1  Checking
1              2   Savings
2              3   Payroll
3              4  Business
4              5     Youth

In [19]:
# check the size of account_types.csv 
account_types_df.shape

(5, 2)

In [20]:
# check datatypes 
account_types_df.dtypes

AccountTypeID    int64
TypeName           str
dtype: object

In [21]:
# check missing values
account_types_df.isnull().sum()

AccountTypeID    0
TypeName         0
dtype: int64

In [22]:
# check duplicates values 
account_types_df.duplicated().sum()

np.int64(0)

In [23]:
# save this file 
account_types_df.to_csv('cleaned_account_types.csv', index=False)

print('Saved file successfully....')

Saved file successfully....

In [24]:
# load account_statuses.csv file

account_statuses_df=pd.read_csv("C:/Users/Sistech Computer/OneDrive/Desktop/sandeep/enterprice-banking-analytics-system/data/raw/account_statuses.csv")
account_statuses_df.head()

   AccountStatusID StatusName
0                1     Active
1                2   Inactive
2                3     Closed

In [25]:
# check the size of account_statuses.csv 
account_statuses_df.shape

(3, 2)

In [26]:
# check datatypes
account_statuses_df.dtypes

AccountStatusID    int64
StatusName           str
dtype: object

In [27]:
# check missing values
account_statuses_df.isnull().sum()

AccountStatusID    0
StatusName         0
dtype: int64

In [28]:
# check duplicates values
account_statuses_df.duplicated().sum()

np.int64(0)

In [29]:
# save this file 
account_statuses_df.to_csv('cleaned_account_statuses_types.csv', index=False)

print('Saved file successfully....')

Saved file successfully....

In [30]:
# load loan_statuses.csv file

loan_statuses_df=pd.read_csv("C:/Users/Sistech Computer/OneDrive/Desktop/sandeep/enterprice-banking-analytics-system/data/raw/loan_statuses.csv")
loan_statuses_df.head()

   LoanStatusID StatusName
0             1     Active
1             2   Paid Off
2             3    Overdue

In [31]:
# check the size of loan_statuses.csv 
loan_statuses_df.shape

(3, 2)

In [32]:
# check datatypes
loan_statuses_df.dtypes

LoanStatusID    int64
StatusName        str
dtype: object

In [33]:
# check missing values
loan_statuses_df.isnull().sum()

LoanStatusID    0
StatusName      0
dtype: int64

In [34]:
# check duplicates values
loan_statuses_df.duplicated().sum()

np.int64(0)

In [35]:
# save this file 
loan_statuses_df.to_csv('cleaned_loan_statuses_types.csv', index=False)

print('Saved file successfully....')

Saved file successfully....

In [36]:
# load transaction_types.csv file

transaction_types_df=pd.read_csv("C:/Users/Sistech Computer/OneDrive/Desktop/sandeep/enterprice-banking-analytics-system/data/raw/transaction_types.csv")
transaction_types_df.head()

   TransactionTypeID    TypeName
0                  1     Deposit
1                  2  Withdrawal
2                  3    Transfer
3                  4     Payment

In [37]:
# check the size of transaction_types.csv
transaction_types_df.shape

(4, 2)

In [38]:
# save this file 
transaction_types_df.to_csv('cleaned_transaction_types.csv', index=False)

print('Saved file successfully....')

Saved file successfully....

In [39]:
# load branches.csv file

branches_df=pd.read_csv("C:/Users/Sistech Computer/OneDrive/Desktop/sandeep/enterprice-banking-analytics-system/data/raw/branches.csv")
branches_df.head()

   BranchID BranchName  AddressID
0         1   Branch 1        733
1         2   Branch 2        511
2         3   Branch 3         27
3         4   Branch 4         97
4         5   Branch 5        796

In [40]:
# check the size of branches.csv file
branches_df.shape

(50, 3)

In [41]:
# check datatypes
branches_df.dtypes

BranchID      int64
BranchName      str
AddressID     int64
dtype: object

In [42]:
# check missing values
branches_df.isnull().sum()

BranchID      0
BranchName    0
AddressID     0
dtype: int64

In [43]:
# check duplicate values
branches_df.duplicated().sum()

np.int64(0)

In [44]:
# save this file 
branches_df.to_csv('cleaned_branches.csv', index=False)

print('Saved file successfully....')

Saved file successfully....

In [45]:
# load customers.csv file

customers_df=pd.read_csv("C:/Users/Sistech Computer/OneDrive/Desktop/sandeep/enterprice-banking-analytics-system/data/raw/customers.csv")
customers_df.head()

,CustomerID,FirstName,LastName,DateOfBirth,AddressID,CustomerTypeID
0,10832,Nyla,Aguirre,1974-02-07 00:00:00.000000,881,1
1,10983,NaN,Battle,1963-02-01 00:00:00.000000,958,2
2,10837,Angelena,Harrington,1964-03-25 00:00:00.000000,86,3
3,10107,Remona,Glass,1965-09-16 00:00:00.000000,595,1
4,10553,King,Becker,1966-02-20 00:00:00.000000,969,3

In [46]:
# check the size of customers.csv file
customers_df.shape

(1111, 6)

In [47]:
# check datatypes
customers_df.dtypes

CustomerID        int64
FirstName           str
LastName            str
DateOfBirth         str
AddressID         int64
CustomerTypeID    int64
dtype: object

In [48]:
# converted DateOfBirth datatype from str to date
customers_df['DateOfBirth']=pd.to_datetime(customers_df['DateOfBirth'], format='mixed', errors='coerce')

In [49]:
# check missing values
customers_df.isnull().sum()

CustomerID         0
FirstName         22
LastName          23
DateOfBirth       24
AddressID          0
CustomerTypeID     0
dtype: int64

In [50]:
# fill missing values

customers_df['FirstName']=customers_df['FirstName'].fillna(customers_df['LastName'])
customers_df['LastName']=customers_df['LastName'].fillna(customers_df['FirstName'])
customers_df=customers_df.dropna()

In [51]:
customers_df.head()

   CustomerID FirstName    LastName DateOfBirth  AddressID  CustomerTypeID
0       10832      Nyla     Aguirre  1974-02-07        881               1
1       10983    Battle      Battle  1963-02-01        958               2
2       10837  Angelena  Harrington  1964-03-25         86               3
3       10107    Remona       Glass  1965-09-16        595               1
4       10553      King      Becker  1966-02-20        969               3

In [52]:
# check duplicate values
customers_df.duplicated().sum()

np.int64(11)

In [53]:
# drop duplicate values
customers_df.drop_duplicates()
customers_df.head()

   CustomerID FirstName    LastName DateOfBirth  AddressID  CustomerTypeID
0       10832      Nyla     Aguirre  1974-02-07        881               1
1       10983    Battle      Battle  1963-02-01        958               2
2       10837  Angelena  Harrington  1964-03-25         86               3
3       10107    Remona       Glass  1965-09-16        595               1
4       10553      King      Becker  1966-02-20        969               3

In [54]:
# save this file 
customers_df.to_csv('cleaned_customers.csv', index=False)

print('Saved file successfully....')

Saved file successfully....

In [55]:
# load accounts.csv file

accounts_df=pd.read_csv("C:/Users/Sistech Computer/OneDrive/Desktop/sandeep/enterprice-banking-analytics-system/data/raw/accounts.csv")
accounts_df.head()

,AccountID,CustomerID,AccountTypeID,AccountStatusID,Balance,OpeningDate
0,200094,10123,3,1,48348.54,2018-06-12 00:00:00.000000
1,201108,10077,3,1,35001.41,2019-10-30 00:00:00.000000
2,201453,10321,3,2,57081.03,2020-05-24 00:00:00.000000
3,200581,10871,5,1,63164.33,2021-01-27 00:00:00.000000
4,200003,10765,1,1,58739.64,2018-09-12 00:00:00.000000

In [56]:
# check the size of accounts.csv file
accounts_df.shape

(1667, 6)

In [57]:
# check datatypes
accounts_df.dtypes

AccountID            int64
CustomerID           int64
AccountTypeID        int64
AccountStatusID      int64
Balance            float64
OpeningDate            str
dtype: object

In [58]:
# convert datatype of OpeningDate from str to datetime
accounts_df['OpeningDate']=pd.to_datetime(accounts_df['OpeningDate'])

accounts_df.dtypes

AccountID                   int64
CustomerID                  int64
AccountTypeID               int64
AccountStatusID             int64
Balance                   float64
OpeningDate        datetime64[us]
dtype: object

In [59]:
# check missing values
accounts_df.isnull().sum()

AccountID           0
CustomerID          0
AccountTypeID       0
AccountStatusID     0
Balance             0
OpeningDate        33
dtype: int64

In [60]:
# drop missing values
accounts_df=accounts_df.dropna()

In [61]:
# check duplicates 
accounts_df.duplicated().sum()

np.int64(16)

In [62]:
# drop duplicates
accounts_df=accounts_df.drop_duplicates()

In [63]:
# save this file 
accounts_df.to_csv('cleaned_accounts.csv', index=False)

print('Saved file successfully....')

Saved file successfully....

In [64]:
# load loans.csv file

loans_df=pd.read_csv("C:/Users/Sistech Computer/OneDrive/Desktop/sandeep/enterprice-banking-analytics-system/data/raw/loans.csv")
loans_df.head()

,LoanID,AccountID,LoanStatusID,PrincipalAmount,InterestRate,StartDate,EstimatedEndDate
0,400230,200876,1,76958.56,0.0547,2022-11-20 00:00:00.000000,2026-08-06 00:00:00.000000
1,400307,200789,1,29013.67,0.0321,2022-02-22 00:00:00.000000,2025-12-08 00:00:00.000000
2,400233,201275,1,48596.76,0.1017,2021-11-21 00:00:00.000000,2023-07-30 00:00:00.000000
3,400100,200070,1,9191.43,0.0999,2021-08-14 00:00:00.000000,2023-09-18 00:00:00.000000
4,400141,200808,1,76322.83,0.0906,2021-06-04 00:00:00.000000,2024-10-23 00:00:00.000000

In [65]:
# check the size of loans.csv file
loans_df.shape

(333, 7)

In [66]:
# check datatypes
loans_df.dtypes

LoanID                int64
AccountID             int64
LoanStatusID          int64
PrincipalAmount     float64
InterestRate        float64
StartDate               str
EstimatedEndDate        str
dtype: object

In [67]:
# converted datatypes from str to datatime
loans_df['StartDate']=pd.to_datetime(loans_df['StartDate'])
loans_df['EstimatedEndDate']=pd.to_datetime(loans_df['EstimatedEndDate'])

In [68]:
# check missing values
loans_df.isnull().sum()

LoanID              0
AccountID           0
LoanStatusID        0
PrincipalAmount     0
InterestRate        0
StartDate           6
EstimatedEndDate    6
dtype: int64

In [69]:
# drop missing values
loans_df=loans_df.dropna()

In [70]:
# check duplicated values
loans_df.duplicated().sum()

np.int64(3)

In [71]:
# drop duplicates 
loans_df=loans_df.drop_duplicates()

In [72]:
# save this file 
loans_df.to_csv('cleaned_loans.csv', index=False)

print('Saved file successfully....')

Saved file successfully....

In [73]:
# load transaction.csv file

transactions_df=pd.read_csv("C:/Users/Sistech Computer/OneDrive/Desktop/sandeep/enterprice-banking-analytics-system/data/raw/transactions.csv")
transactions_df.head()

,TransactionID,AccountOriginID,AccountDestinationID,TransactionTypeID,Amount,TransactionDate,BranchID,Description
0,3022681,201164,200868,2,855.17,2023-04-20 02:00:00.000000,41,Transaction 22681
1,3037846,200138,201402,2,806.20,2021-08-10 15:00:00.000000,43,Transaction 37846
2,3045293,201002,201180,1,1229.44,2020-08-16 03:00:00.000000,5,Transaction 45293
3,3017397,201066,201144,4,4441.60,2021-10-10 06:00:00.000000,14,Transaction 17397
4,3016750,200289,201413,3,2526.20,2022-07-28 00:00:00.000000,37,Transaction 16750

In [74]:
# check the size of transactions.csv file
transactions_df.shape

(50000, 8)

In [75]:
# check datatypes
transactions_df.dtypes

TransactionID             int64
AccountOriginID           int64
AccountDestinationID      int64
TransactionTypeID         int64
Amount                  float64
TransactionDate             str
BranchID                  int64
Description                 str
dtype: object

In [76]:
# converted datatypes of TransactionDate from str to datetime
transactions_df['TransactionDate']=pd.to_datetime(transactions_df['TransactionDate'])

In [77]:
# check missing values
transactions_df.isnull().sum()

TransactionID              0
AccountOriginID            0
AccountDestinationID       0
TransactionTypeID          0
Amount                     0
TransactionDate         1000
BranchID                   0
Description                0
dtype: int64

In [78]:
# drop missing values
transactions_df=transactions_df.dropna()

In [79]:
# check duplicates
transactions_df.duplicated().sum()

np.int64(490)

In [80]:
# drop duplicates
transactions_df=transactions_df.drop_duplicates()

In [81]:
# save this file 
transactions_df.to_csv('cleaned_transactions.csv', index=False)

print('Saved file successfully....')

Saved file successfully....